import { Roboto } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import { Providers } from "./provider";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`} suppressHydrationWarning>
      <body className="bg-background text-foreground" cz-shortcut-listen="true">
        <Providers>
          <NavbarComponent />
          <main className=" min-h-[70vh]">{children}</main>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
